// Database type definitions
// This file will be auto-generated by Supabase CLI in production
// For now, this is a placeholder that matches our schema

export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[]

export interface Database {
  public: {
    Tables: {
      brands: {
        Row: {
          id: string
          user_id: string
          business_name: string
          industry: string | null
          logo_url: string | null
          website: string | null
          uvp_completed: boolean
          onboarding_completed: boolean
          last_enriched_at: string | null
          created_at: string
          updated_at: string
        }
        Insert: {
          id?: string
          user_id: string
          business_name: string
          industry?: string | null
          logo_url?: string | null
          website?: string | null
          uvp_completed?: boolean
          onboarding_completed?: boolean
          last_enriched_at?: string | null
          created_at?: string
          updated_at?: string
        }
        Update: {
          id?: string
          user_id?: string
          business_name?: string
          industry?: string | null
          logo_url?: string | null
          website?: string | null
          uvp_completed?: boolean
          onboarding_completed?: boolean
          last_enriched_at?: string | null
          created_at?: string
          updated_at?: string
        }
      }
      mirror_sections: {
        Row: {
          id: string
          brand_id: string
          section: string
          data: Json
          last_enriched_at: string | null
          auto_enrich_enabled: boolean
          created_at: string
          updated_at: string
        }
        Insert: {
          id?: string
          brand_id: string
          section: string
          data?: Json
          last_enriched_at?: string | null
          auto_enrich_enabled?: boolean
          created_at?: string
          updated_at?: string
        }
        Update: {
          id?: string
          brand_id?: string
          section?: string
          data?: Json
          last_enriched_at?: string | null
          auto_enrich_enabled?: boolean
          created_at?: string
          updated_at?: string
        }
      }
      content_calendar_items: {
        Row: {
          id: string
          brand_id: string
          user_id: string
          pillar_id: string | null
          campaign_id: string | null
          platform: string
          format: string
          status: string
          generation_mode: string | null
          title: string
          body: string
          media_urls: string[]
          hashtags: string[]
          scheduled_for: string | null
          published_at: string | null
          platform_post_id: string | null
          engagement_metrics: Json | null
          design_data: Json | null
          created_at: string
          updated_at: string
        }
        Insert: {
          id?: string
          brand_id: string
          user_id: string
          pillar_id?: string | null
          campaign_id?: string | null
          platform: string
          format: string
          status?: string
          generation_mode?: string | null
          title: string
          body: string
          media_urls?: string[]
          hashtags?: string[]
          scheduled_for?: string | null
          published_at?: string | null
          platform_post_id?: string | null
          engagement_metrics?: Json | null
          design_data?: Json | null
          created_at?: string
          updated_at?: string
        }
        Update: {
          id?: string
          brand_id?: string
          user_id?: string
          pillar_id?: string | null
          campaign_id?: string | null
          platform?: string
          format?: string
          status?: string
          generation_mode?: string | null
          title?: string
          body?: string
          media_urls?: string[]
          hashtags?: string[]
          scheduled_for?: string | null
          published_at?: string | null
          platform_post_id?: string | null
          engagement_metrics?: Json | null
          design_data?: Json | null
          created_at?: string
          updated_at?: string
        }
      }
      marbs_conversations: {
        Row: {
          id: string
          brand_id: string
          user_id: string
          context: Json
          messages: Json
          actions_taken: Json
          created_at: string
          updated_at: string
          last_message_at: string
        }
        Insert: {
          id?: string
          brand_id: string
          user_id: string
          context?: Json
          messages?: Json
          actions_taken?: Json
          created_at?: string
          updated_at?: string
          last_message_at?: string
        }
        Update: {
          id?: string
          brand_id?: string
          user_id?: string
          context?: Json
          messages?: Json
          actions_taken?: Json
          created_at?: string
          updated_at?: string
          last_message_at?: string
        }
      }
      intelligence_opportunities: {
        Row: {
          id: string
          brand_id: string
          type: string
          title: string
          description: string
          source_data: Json
          impact_score: number
          urgency: string
          expires_at: string | null
          status: string
          suggested_actions: string[]
          created_at: string
          actioned_at: string | null
        }
        Insert: {
          id?: string
          brand_id: string
          type: string
          title: string
          description: string
          source_data?: Json
          impact_score: number
          urgency: string
          expires_at?: string | null
          status?: string
          suggested_actions?: string[]
          created_at?: string
          actioned_at?: string | null
        }
        Update: {
          id?: string
          brand_id?: string
          type?: string
          title?: string
          description?: string
          source_data?: Json
          impact_score?: number
          urgency?: string
          expires_at?: string | null
          status?: string
          suggested_actions?: string[]
          created_at?: string
          actioned_at?: string | null
        }
      }
      // Add other tables as needed
    }
    Views: {
      [_ in never]: never
    }
    Functions: {
      [_ in never]: never
    }
    Enums: {
      [_ in never]: never
    }
  }
}
