// Database type definitions
// This file will be auto-generated by Supabase CLI in production
// For now, this is a placeholder that matches our schema

export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[]

export interface Database {
  public: {
    Tables: {
      brands: {
        Row: {
          id: string
          user_id: string
          business_name: string
          industry: string | null
          logo_url: string | null
          website: string | null
          uvp_completed: boolean
          onboarding_completed: boolean
          last_enriched_at: string | null
          emotional_quotient: number | null
          eq_calculated_at: string | null
          created_at: string
          updated_at: string
        }
        Insert: {
          id?: string
          user_id: string
          business_name: string
          industry?: string | null
          logo_url?: string | null
          website?: string | null
          uvp_completed?: boolean
          onboarding_completed?: boolean
          last_enriched_at?: string | null
          emotional_quotient?: number | null
          eq_calculated_at?: string | null
          created_at?: string
          updated_at?: string
        }
        Update: {
          id?: string
          user_id?: string
          business_name?: string
          industry?: string | null
          logo_url?: string | null
          website?: string | null
          uvp_completed?: boolean
          onboarding_completed?: boolean
          last_enriched_at?: string | null
          emotional_quotient?: number | null
          eq_calculated_at?: string | null
          created_at?: string
          updated_at?: string
        }
      }
      brand_eq_scores: {
        Row: {
          id: string
          brand_id: string
          emotional_quotient: number
          rational_quotient: number
          overall_eq: number
          confidence_score: number
          calculation_method: string
          specialty: string | null
          industry: string | null
          is_passion_product: boolean
          specialty_contribution: Json | null
          pattern_contribution: Json | null
          content_contribution: Json | null
          detected_signals: Json | null
          recommendations: Json | null
          calculation_id: string
          calculated_at: string
          created_at: string
          updated_at: string
        }
        Insert: {
          id?: string
          brand_id: string
          emotional_quotient: number
          rational_quotient: number
          overall_eq: number
          confidence_score: number
          calculation_method: string
          specialty?: string | null
          industry?: string | null
          is_passion_product?: boolean
          specialty_contribution?: Json | null
          pattern_contribution?: Json | null
          content_contribution?: Json | null
          detected_signals?: Json | null
          recommendations?: Json | null
          calculation_id: string
          calculated_at?: string
          created_at?: string
          updated_at?: string
        }
        Update: {
          id?: string
          brand_id?: string
          emotional_quotient?: number
          rational_quotient?: number
          overall_eq?: number
          confidence_score?: number
          calculation_method?: string
          specialty?: string | null
          industry?: string | null
          is_passion_product?: boolean
          specialty_contribution?: Json | null
          pattern_contribution?: Json | null
          content_contribution?: Json | null
          detected_signals?: Json | null
          recommendations?: Json | null
          calculation_id?: string
          calculated_at?: string
          created_at?: string
          updated_at?: string
        }
      }
      eq_patterns: {
        Row: {
          id: string
          pattern_id: string
          pattern_type: string
          detected_keywords: string[]
          keyword_density: Json
          has_testimonials: boolean
          has_forums: boolean
          has_pricing_tables: boolean
          has_comparison_charts: boolean
          has_contact_only_pricing: boolean
          calculated_eq: number
          confidence_score: number
          business_name: string | null
          specialty: string | null
          created_at: string
        }
        Insert: {
          id?: string
          pattern_id: string
          pattern_type: string
          detected_keywords: string[]
          keyword_density: Json
          has_testimonials?: boolean
          has_forums?: boolean
          has_pricing_tables?: boolean
          has_comparison_charts?: boolean
          has_contact_only_pricing?: boolean
          calculated_eq: number
          confidence_score: number
          business_name?: string | null
          specialty?: string | null
          created_at?: string
        }
        Update: {
          id?: string
          pattern_id?: string
          pattern_type?: string
          detected_keywords?: string[]
          keyword_density?: Json
          has_testimonials?: boolean
          has_forums?: boolean
          has_pricing_tables?: boolean
          has_comparison_charts?: boolean
          has_contact_only_pricing?: boolean
          calculated_eq?: number
          confidence_score?: number
          business_name?: string | null
          specialty?: string | null
          created_at?: string
        }
      }
      eq_specialty_baselines: {
        Row: {
          id: string
          specialty: string
          base_eq: number
          is_passion_product: boolean
          sample_size: number
          confidence_score: number
          example_businesses: string[]
          avg_emotional_density: number | null
          avg_rational_density: number | null
          common_signals: string[]
          first_learned_at: string
          last_updated_at: string
          created_at: string
        }
        Insert: {
          id?: string
          specialty: string
          base_eq: number
          is_passion_product?: boolean
          sample_size?: number
          confidence_score: number
          example_businesses?: string[]
          avg_emotional_density?: number | null
          avg_rational_density?: number | null
          common_signals?: string[]
          first_learned_at?: string
          last_updated_at?: string
          created_at?: string
        }
        Update: {
          id?: string
          specialty?: string
          base_eq?: number
          is_passion_product?: boolean
          sample_size?: number
          confidence_score?: number
          example_businesses?: string[]
          avg_emotional_density?: number | null
          avg_rational_density?: number | null
          common_signals?: string[]
          first_learned_at?: string
          last_updated_at?: string
          created_at?: string
        }
      }
      eq_performance_metrics: {
        Row: {
          id: string
          brand_id: string
          content_id: string | null
          content_type: string
          platform: string
          content_eq: number
          target_eq: number | null
          eq_variance: number | null
          platform_adjustment: number
          seasonal_adjustment: number
          campaign_type_adjustment: number
          impressions: number
          engagement_count: number
          engagement_rate: number | null
          click_count: number
          click_rate: number | null
          conversion_count: number
          conversion_rate: number | null
          published_at: string | null
          measured_at: string
          created_at: string
        }
        Insert: {
          id?: string
          brand_id: string
          content_id?: string | null
          content_type: string
          platform: string
          content_eq: number
          target_eq?: number | null
          eq_variance?: number | null
          platform_adjustment?: number
          seasonal_adjustment?: number
          campaign_type_adjustment?: number
          impressions?: number
          engagement_count?: number
          engagement_rate?: number | null
          click_count?: number
          click_rate?: number | null
          conversion_count?: number
          conversion_rate?: number | null
          published_at?: string | null
          measured_at?: string
          created_at?: string
        }
        Update: {
          id?: string
          brand_id?: string
          content_id?: string | null
          content_type?: string
          platform?: string
          content_eq?: number
          target_eq?: number | null
          eq_variance?: number | null
          platform_adjustment?: number
          seasonal_adjustment?: number
          campaign_type_adjustment?: number
          impressions?: number
          engagement_count?: number
          engagement_rate?: number | null
          click_count?: number
          click_rate?: number | null
          conversion_count?: number
          conversion_rate?: number | null
          published_at?: string | null
          measured_at?: string
          created_at?: string
        }
      }
      mirror_sections: {
        Row: {
          id: string
          brand_id: string
          section: string
          data: Json
          last_enriched_at: string | null
          auto_enrich_enabled: boolean
          created_at: string
          updated_at: string
        }
        Insert: {
          id?: string
          brand_id: string
          section: string
          data?: Json
          last_enriched_at?: string | null
          auto_enrich_enabled?: boolean
          created_at?: string
          updated_at?: string
        }
        Update: {
          id?: string
          brand_id?: string
          section?: string
          data?: Json
          last_enriched_at?: string | null
          auto_enrich_enabled?: boolean
          created_at?: string
          updated_at?: string
        }
      }
      content_calendar_items: {
        Row: {
          id: string
          brand_id: string
          user_id: string
          pillar_id: string | null
          campaign_id: string | null
          platform: string
          format: string
          status: string
          generation_mode: string | null
          title: string
          body: string
          media_urls: string[]
          hashtags: string[]
          scheduled_for: string | null
          published_at: string | null
          platform_post_id: string | null
          engagement_metrics: Json | null
          design_data: Json | null
          created_at: string
          updated_at: string
        }
        Insert: {
          id?: string
          brand_id: string
          user_id: string
          pillar_id?: string | null
          campaign_id?: string | null
          platform: string
          format: string
          status?: string
          generation_mode?: string | null
          title: string
          body: string
          media_urls?: string[]
          hashtags?: string[]
          scheduled_for?: string | null
          published_at?: string | null
          platform_post_id?: string | null
          engagement_metrics?: Json | null
          design_data?: Json | null
          created_at?: string
          updated_at?: string
        }
        Update: {
          id?: string
          brand_id?: string
          user_id?: string
          pillar_id?: string | null
          campaign_id?: string | null
          platform?: string
          format?: string
          status?: string
          generation_mode?: string | null
          title?: string
          body?: string
          media_urls?: string[]
          hashtags?: string[]
          scheduled_for?: string | null
          published_at?: string | null
          platform_post_id?: string | null
          engagement_metrics?: Json | null
          design_data?: Json | null
          created_at?: string
          updated_at?: string
        }
      }
      marbs_conversations: {
        Row: {
          id: string
          brand_id: string
          user_id: string
          context: Json
          messages: Json
          actions_taken: Json
          created_at: string
          updated_at: string
          last_message_at: string
        }
        Insert: {
          id?: string
          brand_id: string
          user_id: string
          context?: Json
          messages?: Json
          actions_taken?: Json
          created_at?: string
          updated_at?: string
          last_message_at?: string
        }
        Update: {
          id?: string
          brand_id?: string
          user_id?: string
          context?: Json
          messages?: Json
          actions_taken?: Json
          created_at?: string
          updated_at?: string
          last_message_at?: string
        }
      }
      intelligence_opportunities: {
        Row: {
          id: string
          brand_id: string
          type: string
          title: string
          description: string
          source_data: Json
          impact_score: number
          urgency: string
          expires_at: string | null
          status: string
          suggested_actions: string[]
          created_at: string
          actioned_at: string | null
        }
        Insert: {
          id?: string
          brand_id: string
          type: string
          title: string
          description: string
          source_data?: Json
          impact_score: number
          urgency: string
          expires_at?: string | null
          status?: string
          suggested_actions?: string[]
          created_at?: string
          actioned_at?: string | null
        }
        Update: {
          id?: string
          brand_id?: string
          type?: string
          title?: string
          description?: string
          source_data?: Json
          impact_score?: number
          urgency?: string
          expires_at?: string | null
          status?: string
          suggested_actions?: string[]
          created_at?: string
          actioned_at?: string | null
        }
      }
      // ========== Foundation Schema Tables (30 tables) ==========
      naics_codes: {
        Row: {
          id: string
          code: string
          title: string
          description: string | null
          level: number
          parent_code: string | null
          created_at: string
          updated_at: string
        }
        Insert: {
          id?: string
          code: string
          title: string
          description?: string | null
          level: number
          parent_code?: string | null
          created_at?: string
          updated_at?: string
        }
        Update: {
          id?: string
          code?: string
          title?: string
          description?: string | null
          level?: number
          parent_code?: string | null
          updated_at?: string
        }
      }
      business_profiles: {
        Row: {
          id: string
          user_id: string
          business_name: string
          website_url: string | null
          naics_code: string | null
          specialty: string | null
          founded_year: number | null
          employee_count: string | null
          annual_revenue_range: string | null
          business_model: string | null
          description: string | null
          logo_url: string | null
          created_at: string
          updated_at: string
        }
        Insert: {
          id?: string
          user_id: string
          business_name: string
          website_url?: string | null
          naics_code?: string | null
          specialty?: string | null
          founded_year?: number | null
          employee_count?: string | null
          annual_revenue_range?: string | null
          business_model?: string | null
          description?: string | null
          logo_url?: string | null
          created_at?: string
          updated_at?: string
        }
        Update: {
          id?: string
          user_id?: string
          business_name?: string
          website_url?: string | null
          naics_code?: string | null
          specialty?: string | null
          founded_year?: number | null
          employee_count?: string | null
          annual_revenue_range?: string | null
          business_model?: string | null
          description?: string | null
          logo_url?: string | null
          updated_at?: string
        }
      }
      intelligence_cache: {
        Row: {
          id: string
          cache_key: string
          data: Json
          expires_at: string
          created_at: string
        }
        Insert: {
          id?: string
          cache_key: string
          data: Json
          expires_at: string
          created_at?: string
        }
        Update: {
          cache_key?: string
          data?: Json
          expires_at?: string
        }
      }
      uvp_statements: {
        Row: {
          id: string
          business_id: string
          statement: string
          variant_type: string | null
          target_audience: string | null
          confidence_score: number | null
          is_active: boolean
          created_at: string
          updated_at: string
        }
        Insert: {
          id?: string
          business_id: string
          statement: string
          variant_type?: string | null
          target_audience?: string | null
          confidence_score?: number | null
          is_active?: boolean
          created_at?: string
          updated_at?: string
        }
        Update: {
          business_id?: string
          statement?: string
          variant_type?: string | null
          target_audience?: string | null
          confidence_score?: number | null
          is_active?: boolean
          updated_at?: string
        }
      }
      content_pieces: {
        Row: {
          id: string
          business_id: string
          campaign_id: string | null
          content_type: string
          platform: string | null
          title: string | null
          content_text: string | null
          media_urls: Json | null
          hashtags: Json | null
          status: string
          scheduled_for: string | null
          published_at: string | null
          created_at: string
          updated_at: string
        }
        Insert: {
          id?: string
          business_id: string
          campaign_id?: string | null
          content_type: string
          platform?: string | null
          title?: string | null
          content_text?: string | null
          media_urls?: Json | null
          hashtags?: Json | null
          status?: string
          scheduled_for?: string | null
          published_at?: string | null
          created_at?: string
          updated_at?: string
        }
        Update: {
          business_id?: string
          campaign_id?: string | null
          content_type?: string
          platform?: string | null
          title?: string | null
          content_text?: string | null
          media_urls?: Json | null
          hashtags?: Json | null
          status?: string
          scheduled_for?: string | null
          published_at?: string | null
          updated_at?: string
        }
      }
      generated_visuals: {
        Row: {
          id: string
          brand_id: string
          campaign_id: string | null
          campaign_type: string
          platform: string
          format: string
          image_url: string
          bannerbear_uid: string
          template_id: string
          content_snapshot: Json
          dimensions: Json
          aspect_ratio: string
          generation_time_ms: number
          status: string
          error_message: string | null
          created_at: string
          updated_at: string
        }
        Insert: {
          id?: string
          brand_id: string
          campaign_id?: string | null
          campaign_type: string
          platform: string
          format: string
          image_url: string
          bannerbear_uid: string
          template_id: string
          content_snapshot?: Json
          dimensions: Json
          aspect_ratio: string
          generation_time_ms: number
          status: string
          error_message?: string | null
          created_at?: string
          updated_at?: string
        }
        Update: {
          id?: string
          brand_id?: string
          campaign_id?: string | null
          campaign_type?: string
          platform?: string
          format?: string
          image_url?: string
          bannerbear_uid?: string
          template_id?: string
          content_snapshot?: Json
          dimensions?: Json
          aspect_ratio?: string
          generation_time_ms?: number
          status?: string
          error_message?: string | null
          updated_at?: string
        }
      }
      // Note: Remaining 25 foundation tables follow the same pattern
      // They will be auto-generated when the migration runs on Supabase
    }
    Views: {
      [_ in never]: never
    }
    Functions: {
      [_ in never]: never
    }
    Enums: {
      [_ in never]: never
    }
  }
}
