// Central export file for all type definitions

// Note: mirror.types.ts has been removed/consolidated into other type files

// UVP (Unique Value Proposition) types
export type {
  ValueStatementStatus,
  UVPContext,
  ValueStatement,
  UVPPerformanceData,
  UVPComponentType,
  ComponentSource,
  UVPComponent,
  ABTestStatus,
  ABTestWinner,
  UVPABTest,
  UVPABTestWithVariants,
  ValueStatementFormData,
  UVPFormula,
  UVPTemplate,
  UVPScoreBreakdown,
  CompetitiveUVPAnalysis,
  UVPBrandHealthImpact,
  UVPFlowTab,
  UVPBuilderMode,
  UVPContextState,
  UVPContextActions,
  UVPExportFormat,
  UVPExportConfig,
  UVPValidationResult,
  UVPGenerationRequest,
  UVPGenerationResponse,
} from './uvp.types';

// Note: Marbs AI Assistant types removed - marbs.types.ts file doesn't exist
// TODO: Create marbs.types.ts if Marbs functionality is needed

// Content types
export type {
  ContentGenerationMode,
  ContentStatus,
  ContentPlatform,
  ContentFormat,
  ContentCalendarItem,
  ContentVariation,
  EngagementMetrics,
  // DesignData moved to design-studio.types
  DesignObject,
  TextData,
  ImageData,
  ShapeData,
  DesignBackground,
  DesignTemplate,
  ContentGenerationRequest,
  ContentGenerationResponse,
  ContentGenerationMetadata,
  SynapseEnrichment,
  SynapseConnection,
  PublishRequest,
  PublishResponse,
  // ContentPerformance moved to analytics.types
  BenchmarkComparison,
  CalendarView,
  CalendarFilters,
  CalendarEvent,
} from './content.types';

// MARBA Score types
export type {
  MARBAScore,
  MARBABreakdown,
  MessagingScore,
  AuthenticityScore,
  RelevanceScore,
  BrandAlignmentScore,
  ActionScore,
  ComponentScore,
  MARBAInsight,
  MARBAAnalysisContext,
  BrandGuidelines,
  MARBAScoreHistory,
  MARBAScoreSnapshot,
  MARBABenchmark,
  MARBAOptimization,
  OptimizationSuggestion,
  MARBAComparison,
  MARBAABTest,
  ContentPerformanceMetrics,
  RealtimeMARBAScore,
} from './marba-score.types';

// Intelligence types
export type {
  IndustryProfile,
  CustomerTrigger,
  SeasonalityData,
  SeasonalTrend,
  BuyingJourneyStage,
  BenchmarkMetrics,
  SynapseAnalysis,
  Connection,
  PowerWord,
  EmotionalTrigger,
  PersuasionElement,
  OpportunityInsight,
  OpportunityType,
  OpportunitySource,
  SuggestedAction,
  // LearningPattern and PatternEvidence moved to analytics.types
  CompetitiveSnapshot,
  CompetitorMetrics,
  CompetitorContentAnalysis,
  ContentSummary,
  AnalyticsEvent,
  PlatformMetricsSnapshot,
  PlatformMetrics,
  MetricComparisons,
  EngagementInboxItem,
} from './intelligence.types';

// API types
export type {
  APIResponse,
  APIError,
  AnalyzeMirrorRequest,
  AnalyzeMirrorResponse,
  GenerateContentRequest,
  GenerateContentResponse,
  EnrichWithSynapseRequest,
  EnrichWithSynapseResponse,
  PublishToPlatformRequest,
  PublishToPlatformResponse,
  CollectAnalyticsRequest,
  CollectAnalyticsResponse,
  MarbsMessageRequest,
  MarbsMessageResponse,
  CalculateMARBAScoreRequest,
  CalculateMARBAScoreResponse,
  OpenRouterRequest,
  OpenRouterMessage,
  OpenRouterResponse,
  FacebookGraphAPIRequest,
  FacebookGraphAPIResponse,
  LinkedInShareRequest,
  LinkedInShareResponse,
  TwitterTweetRequest,
  TwitterTweetResponse,
  GoogleBusinessPostRequest,
  GoogleBusinessPostResponse,
  EdgeFunctionRequest,
  EdgeFunctionResponse,
  WebhookPayload,
  WebhookResponse,
} from './api.types';

// Analytics types
export type {
  OnTrackStatus,
  GoalProgress,
  Projection,
  ChangeDirection,
  KPIMetric,
  Comparison,
  Platform,
  ContentPerformance,
  ContentItem,
  PlatformPerformance,
  PillarPerformance,
  OptimalTimes,
  Demographics,
  GrowthData,
  Heatmap,
  SentimentData,
  EngagementType,
  SentimentType,
  PriorityLevel,
  EngagementStatus,
  EngagementItem,
  ResponseSuggestion,
  InboxFilters,
  PatternType,
  LearningPattern,
  PatternEvidence,
  CompetitiveActivityType,
  ImpactLevel,
  CompetitiveActivity,
  GapType,
  CompetitiveGap,
  CompetitorComparison,
  DateRange,
  AnalyticsFilters,
  ExportOptions,
  ExportResult,
  AnalyticsSummary,
  PowerWordPerformance,
  PostingInsight,
  ContentTypePerformance,
  ROIMetrics,
  ConversionFunnel,
} from './analytics.types';

// Design Studio types
export type {
  DesignData,
  ExportOptions as DesignExportOptions,
  Template,
  ShapeType,
  ToolType,
  CanvasState,
  PlatformPreset,
  BrandAsset,
  UnsplashPhoto,
  LayerInfo,
  TextProperties,
  ShapeProperties,
  ImageFilter,
  ImageProperties,
  TransformProperties,
  TemplateCategory,
} from './design-studio.types';

export { PLATFORM_PRESETS, DEFAULT_FONTS, GOOGLE_FONTS, KEYBOARD_SHORTCUTS } from './design-studio.types';
