-- V4 Generated Content Table
-- Stores content generated by the V4 Content Engine
-- Created: 2025-11-27

-- Drop if exists (for clean migrations)
DROP TABLE IF EXISTS v4_generated_content CASCADE;

-- Create the table
CREATE TABLE v4_generated_content (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),

  -- Foreign keys
  brand_id UUID REFERENCES brands(id) ON DELETE CASCADE,
  user_id UUID REFERENCES auth.users(id) ON DELETE SET NULL,
  uvp_id UUID REFERENCES marba_uvps(id) ON DELETE SET NULL,

  -- Content structure
  headline TEXT NOT NULL,
  hook TEXT NOT NULL,
  body TEXT NOT NULL,
  cta TEXT NOT NULL,
  hashtags TEXT[] DEFAULT ARRAY[]::TEXT[],

  -- V4 Engine Metadata
  score_total INTEGER NOT NULL CHECK (score_total >= 0 AND score_total <= 100),
  score_breakdown JSONB NOT NULL DEFAULT '{}'::JSONB,
  -- Example: {"unexpectedness": 25, "truthfulness": 20, "actionability": 15, "uniqueness": 12, "virality": 8}

  score_prediction TEXT NOT NULL CHECK (score_prediction IN ('meh', 'good', 'great', 'holy shit')),
  score_reasoning TEXT[] DEFAULT ARRAY[]::TEXT[],
  score_strengths TEXT[] DEFAULT ARRAY[]::TEXT[],
  score_weaknesses TEXT[] DEFAULT ARRAY[]::TEXT[],

  -- Psychology
  psychology_framework TEXT NOT NULL,
  -- Options: AIDA, PAS, BAB, PASTOR, StoryBrand, CuriosityGap, PatternInterrupt, SocialProof, Scarcity, Reciprocity, LossAversion

  psychology_primary_trigger TEXT NOT NULL,
  psychology_secondary_trigger TEXT,
  psychology_intensity DECIMAL(3,2) NOT NULL CHECK (psychology_intensity >= 0 AND psychology_intensity <= 1),

  -- Content Classification
  mix_category TEXT NOT NULL CHECK (mix_category IN ('value', 'curated', 'promo', 'personal', 'soft_sell', 'hard_sell')),
  funnel_stage TEXT NOT NULL CHECK (funnel_stage IN ('TOFU', 'MOFU', 'BOFU')),
  pillar_id TEXT,
  pillar_name TEXT,

  -- Platform
  platform TEXT NOT NULL CHECK (platform IN ('linkedin', 'instagram', 'twitter', 'facebook', 'tiktok')),
  character_count INTEGER NOT NULL,

  -- Campaign Context
  campaign_id UUID,
  campaign_template TEXT,
  campaign_week INTEGER,

  -- Generation Metadata
  model TEXT NOT NULL DEFAULT 'claude-sonnet-4-20250514',
  generation_mode TEXT NOT NULL CHECK (generation_mode IN ('easy', 'power', 'mixer')),

  -- Deduplication
  content_hash TEXT,

  -- Status
  status TEXT NOT NULL DEFAULT 'draft' CHECK (status IN ('draft', 'scheduled', 'published', 'archived')),
  scheduled_for TIMESTAMPTZ,
  published_at TIMESTAMPTZ,

  -- Timestamps
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- Create indexes for common queries
CREATE INDEX idx_v4_content_brand_id ON v4_generated_content(brand_id);
CREATE INDEX idx_v4_content_user_id ON v4_generated_content(user_id);
CREATE INDEX idx_v4_content_uvp_id ON v4_generated_content(uvp_id);
CREATE INDEX idx_v4_content_platform ON v4_generated_content(platform);
CREATE INDEX idx_v4_content_status ON v4_generated_content(status);
CREATE INDEX idx_v4_content_funnel_stage ON v4_generated_content(funnel_stage);
CREATE INDEX idx_v4_content_mix_category ON v4_generated_content(mix_category);
CREATE INDEX idx_v4_content_created_at ON v4_generated_content(created_at DESC);
CREATE INDEX idx_v4_content_score ON v4_generated_content(score_total DESC);
CREATE INDEX idx_v4_content_campaign ON v4_generated_content(campaign_id) WHERE campaign_id IS NOT NULL;
CREATE INDEX idx_v4_content_hash ON v4_generated_content(content_hash) WHERE content_hash IS NOT NULL;

-- Enable RLS
ALTER TABLE v4_generated_content ENABLE ROW LEVEL SECURITY;

-- RLS Policies
-- Allow users to read their own content
CREATE POLICY "Users can read own content"
  ON v4_generated_content FOR SELECT
  USING (auth.uid() = user_id OR user_id IS NULL);

-- Allow users to insert content
CREATE POLICY "Users can insert content"
  ON v4_generated_content FOR INSERT
  WITH CHECK (auth.uid() = user_id OR user_id IS NULL);

-- Allow users to update their own content
CREATE POLICY "Users can update own content"
  ON v4_generated_content FOR UPDATE
  USING (auth.uid() = user_id OR user_id IS NULL);

-- Allow users to delete their own content
CREATE POLICY "Users can delete own content"
  ON v4_generated_content FOR DELETE
  USING (auth.uid() = user_id OR user_id IS NULL);

-- Allow anonymous access for demo mode
CREATE POLICY "Anonymous access for demo"
  ON v4_generated_content FOR ALL
  USING (user_id IS NULL)
  WITH CHECK (user_id IS NULL);

-- Trigger to update updated_at timestamp
CREATE OR REPLACE FUNCTION update_v4_content_updated_at()
RETURNS TRIGGER AS $$
BEGIN
  NEW.updated_at = NOW();
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER trigger_v4_content_updated_at
  BEFORE UPDATE ON v4_generated_content
  FOR EACH ROW
  EXECUTE FUNCTION update_v4_content_updated_at();

-- V4 Campaigns Table (for campaign tracking)
DROP TABLE IF EXISTS v4_campaigns CASCADE;

CREATE TABLE v4_campaigns (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),

  -- Foreign keys
  brand_id UUID REFERENCES brands(id) ON DELETE CASCADE,
  user_id UUID REFERENCES auth.users(id) ON DELETE SET NULL,
  uvp_id UUID REFERENCES marba_uvps(id) ON DELETE SET NULL,

  -- Campaign details
  name TEXT NOT NULL,
  template_type TEXT NOT NULL CHECK (template_type IN ('product_launch', 'evergreen', 'awareness_burst', 'authority_builder', 'engagement_drive')),
  mix_rule TEXT NOT NULL CHECK (mix_rule IN ('70-20-10', '4-1-1', '5-3-2')),

  -- Duration
  week_count INTEGER NOT NULL,
  posts_per_week INTEGER NOT NULL DEFAULT 5,

  -- Summary
  summary TEXT,
  recommendations TEXT[] DEFAULT ARRAY[]::TEXT[],

  -- Stats
  total_content_count INTEGER NOT NULL DEFAULT 0,
  average_score INTEGER,

  -- Status
  status TEXT NOT NULL DEFAULT 'active' CHECK (status IN ('active', 'completed', 'paused', 'archived')),

  -- Timestamps
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  completed_at TIMESTAMPTZ
);

-- Indexes
CREATE INDEX idx_v4_campaigns_brand_id ON v4_campaigns(brand_id);
CREATE INDEX idx_v4_campaigns_user_id ON v4_campaigns(user_id);
CREATE INDEX idx_v4_campaigns_status ON v4_campaigns(status);

-- Enable RLS
ALTER TABLE v4_campaigns ENABLE ROW LEVEL SECURITY;

-- RLS Policies for campaigns
CREATE POLICY "Users can read own campaigns"
  ON v4_campaigns FOR SELECT
  USING (auth.uid() = user_id OR user_id IS NULL);

CREATE POLICY "Users can insert campaigns"
  ON v4_campaigns FOR INSERT
  WITH CHECK (auth.uid() = user_id OR user_id IS NULL);

CREATE POLICY "Users can update own campaigns"
  ON v4_campaigns FOR UPDATE
  USING (auth.uid() = user_id OR user_id IS NULL);

CREATE POLICY "Users can delete own campaigns"
  ON v4_campaigns FOR DELETE
  USING (auth.uid() = user_id OR user_id IS NULL);

CREATE POLICY "Anonymous access for demo campaigns"
  ON v4_campaigns FOR ALL
  USING (user_id IS NULL)
  WITH CHECK (user_id IS NULL);

-- Trigger for campaigns updated_at
CREATE TRIGGER trigger_v4_campaigns_updated_at
  BEFORE UPDATE ON v4_campaigns
  FOR EACH ROW
  EXECUTE FUNCTION update_v4_content_updated_at();

-- Comment on tables
COMMENT ON TABLE v4_generated_content IS 'Content generated by the V4 Content Engine with full scoring and psychology metadata';
COMMENT ON TABLE v4_campaigns IS 'Campaigns created using V4 Content Engine templates';
